# Build Stage
FROM golang:1.19-alpine as builder

WORKDIR /src
COPY . .
RUN go mod download
ENV VERSION=localdev

WORKDIR usermgm
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o usermgm . && \
	if [ ! -f env/config ]; then cp env/sample.config env/config ; fi

# Run Stage
FROM alpine:latest
COPY --from=builder /src/usermgm .

CMD ["./usermgm"]